inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Airbnb/SimpleModifierConditional:
  Enabled: false

Airbnb/SimpleUnless:
  Enabled: false
