version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    command: bundle exec puma -C config/puma/production.rb -e production
  web:
    build:
      context: containers/nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
volumes:
  public-data:
  tmp-data:
  log-data:
