version: '3'
services:
  web:
    build: .
    volumes:
      - .:/reserve_space
    ports:
      - '3000:3000'
    environment:
      GOOGLE_MAPS_APIKEY: ${GOOGLE_MAPS_APIKEY}
      PAYJP_TEST_OPEN_KEY: ${PAYJP_TEST_OPEN_KEY}
      PAYJP_TEST_SECRET_KEY: ${PAYJP_TEST_SECRET_KEY}
      PAYJP_CREATE_CHARGE_URL: ${PAYJP_CREATE_CHARGE_URL}
      PAYJP_RETRIEVE_CHARGE_URL: ${PAYJP_RETRIEVE_CHARGE_URL}
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bundle exec rails s -b 0.0.0.0
  db:
    image: postgres:12.3
    volumes:
      - pgdatavol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pgdatavol:
