version: '3'
services:
  app:
    build: ./Dockerfile
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    environment:
      GOOGLE_MAPS_APIKEY: ${GOOGLE_MAPS_APIKEY}
      PAYJP_TEST_OPEN_KEY: ${PAYJP_TEST_OPEN_KEY}
      PAYJP_TEST_SECRET_KEY: ${PAYJP_TEST_SECRET_KEY}
      PAYJP_CREATE_CHARGE_URL: ${PAYJP_CREATE_CHARGE_URL}
      PAYJP_RETRIEVE_CHARGE_URL: ${PAYJP_RETRIEVE_CHARGE_URL}
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bundle exec puma -C config/puma.rb
  web:
    build:
      context: containers/development/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
  db:
    image: postgres:12.3
    volumes:
      - pgdatavol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
volumes:
  pgdatavol:
  public-data:
  tmp-data:
  log-data:
